name: GitHub
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  publish:
      - run: git config user.name tylerthayn
      - run: git config user.email tylerthayn@hotmail.com
      - run: git add .
      - run: git commit -m "generated"
      - run: git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
