name: GitHub
on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string
    secrets:
      GITHUB_TOKEN2:
        required: true
        
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
  workflow_dispatch:
  
jobs:
  reusable_workflow_job:
    runs-on: ubuntu-latest
    environment: production
    
    steps:
      - uses: actions/checkout@v2
        with:
          username: ${{ inputs.username }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: git config user.name tylerthayn
      - run: git config user.email tylerthayn@hotmail.com
      - run: git add .
      - run: git commit -m "generated"
      - run: git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
  publish:
    runs-on: ubuntu-latest
    environment: production
    
    steps:
      - uses: actions/checkout@v2
      - run: git config user.name tylerthayn
      - run: git config user.email tylerthayn@hotmail.com
      - run: git add .
      - run: git commit -m "generated"
      - run: git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
