# This is a basic workflow to help you get started with Actions

name: UpdateVersion
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm run-script rev
      
  call-workflow-passing-data:
    uses: tylerthayn/js.core/.github/workflows/github.yml@main
    with:
      username: tylerthayn



