name: UpdateVersion
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm run-script rev
      
  call-workflow:
    uses: .github/workflows/github.yml@v1

